### PR TITLE
Prevent click propagation and collapsing tree on mobile browsers

### LINKED ISSUE #67: Prevent adding layer while expanding Layer-Control on mobile
Hi @jjimenezshaw 

This issue is related to https://github.com/Leaflet/Leaflet/issues/8778 that was fixed in Leaflet 1.9.4 with https://github.com/Leaflet/Leaflet/pull/8910

However, the PR only fix the `L.control.layers`. Using `Leaflet.Control.Layers.Tree` it keeps with the same behaviour, as you can test here:

https://plnkr.co/edit/W135NFAEtQV0a3ZK

https://run.plnkr.co/plunks/W135NFAEtQV0a3ZK

It seems that the fix applied to L.control.layers also needs to be added in `Leaflet.Control.Layers.Tree`

### PR DESCRIPTION
**Pull request by Falke-Design**
Uses the same solution as Leaflet to fix click propagation on mbile browsers.
https://github.com/Leaflet/Leaflet/issues/8778, https://github.com/Leaflet/Leaflet/pull/8910

Fixes: #67

@PedroVenancio, @jjimenezshaw

### CODE REVIEW

**Comment by PedroVenancio** [comment]
Wonderful @Falke-Design It works like a charm!! 

Thank you very much!!

**Comment by albfan** [comment]
I think this is merged, should this be closed?

**Comment by jjimenezshaw** [comment]
> I think this is merged, should this be closed?

I have not merged it. I have had no time to test it, and probably I will have not time the next couple of weeks, sorry, I hope in July I can do it.

**Comment by albfan** [comment]
hmm, sorry I check it wrong. Removing the noise

**Comment by jjimenezshaw** [comment]
Hi.
Finally I have been testing it with `examples/basic.html` (updating to 1.9.4) and it works if I click on the radio button.
However it does not work properly if I click on the label next to the first radio button, `OSM`. It collapses the group. In the label `Open TopoMap` it seems to work properly.
Do you know why?

**Comment by jjimenezshaw** [comment]
Sorry for the late response. I thought that a strange behaviour was due to these changes, but I confirmed that it was there before.
Do you need a release for that?

**Pull request merged**
