### PR TITLE
Add possibility to collapse specific nodes

### PR DESCRIPTION
**Pull request by ybasket**
For large trees (esp. deeply nested ones), it might not be desired to have them all expanded or collapsed initially, but only some parts. This PR adds the possibility to set a `collapsed` flag on each tree node so that this can be controlled more fine-grained, for example by expanding only path based on user selection or only the first n levels, leaving the rest collapsed.

### CODE REVIEW

**Comment by jjimenezshaw** [comment]
Sounds good.
Could you add some tests? Have a look at the section `Expand and collapse`.

BTW, what I do to expand only the selected one is `collapseTree(...).expandSelected(...)`.

**Comment by jjimenezshaw** [comment]
Did you see the tests that are already there? They can be useful. Just take one as a reference from `Expand and collapse`.

**Comment by jjimenezshaw** [comment]
hi @ybasket 
I have done some tests for your PR, but I cannot commit/push in your branch. Could you give me permission? Thanks

**Comment by ybasket** [comment]
Hey @jjimenezshaw, you should now have push permission. Sorry for not getting back on this PR, I completely forgot about it…

**Comment by jjimenezshaw** [comment]
I tried again, and it still fails:
`remote: Permission to Free2MoveApp/Leaflet.Control.Layers.Tree.git denied to jjimenezshaw.
fatal: unable to access 'https://github.com/Free2MoveApp/Leaflet.Control.Layers.Tree.git/': The requested URL returned error: 403
`

**Review by jjimenezshaw — APPROVED** [review]

**Pull request merged**
